site_name: RNA Framework
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
pages:
    - 'Overview': 'index.md'
    - 'Framework components': 'components.md'
    - 'rf-index': 'rf-index.md'
    - 'rf-map': 'rf-map.md'
    - 'rf-count': 'rf-count.md'
    - 'rf-rctools': 'rf-rctools.md'
    - 'rf-norm': 'rf-norm.md'
    - 'rf-fold': 'rf-fold.md'
    - 'rf-duplex': 'rf-duplex.md'
    - 'rf-jackknife': 'rf-jackknife.md'
    - 'rf-compare': 'rf-compare.md'
    - 'rf-modcall': 'rf-modcall.md'
    - 'rf-peakcall': 'rf-peakcall.md'
    - 'rf-motifdiscovery': 'rf-motifdiscovery.md'
    - 'rf-combine': 'rf-combine.md'
    - 'rf-correlate': 'rf-correlate.md'
    - 'rf-wiggle': 'rf-wiggle.md'
    - 'rf-mutate': 'rf-mutate.md'
    - 'rf-json2rc': 'rf-json2rc.md'
    - 'Application cases': 'cases.md'
markdown_extensions:
    - markdown.extensions.admonition
